
package tw.com.bluetechnology.ticket.wsdl.ticketservice.v1_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import tw.com.bluetechnology.ticket.xsd.ticketservice.v1_0.TicketSeatInquiryRequest;
import tw.com.bluetechnology.ticket.xsd.ticketservice.v1_0.TicketSeatInquiryResultResponse;
import tw.com.bluetechnology.ticket.xsd.ticketservice.v1_0.TicketSeatOrderInquiryRequest;
import tw.com.bluetechnology.ticket.xsd.ticketservice.v1_0.TicketSeatOrderInquiryResultResponse;

/**
 * This class was generated by Apache CXF 2.0.6
 * Fri Nov 08 13:20:32 CST 2013
 * Generated source version: 2.0.6
 * 
 */

@WebService(targetNamespace = "http://www.bluetechnology.com.tw/Ticket/wsdl/TicketService/v1-0", name = "TicketPortType")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)

public interface TicketPortType {

	/**
	 * 獲得班機剩餘座位資訊
	 * @param 查詢剩餘座位資訊輸入物件 {@link TicketSeatInquiryRequest}
	 * @return 查詢剩餘座位資訊回傳物件 {@link TicketSeatInquiryResultResponse}
	 */
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "ticketSeatInquiryResultResponse", targetNamespace = "http://www.bluetechnology.com.tw/Ticket/xsd/TicketService/v1-0", partName = "body")
    @WebMethod(action = "http://www.blueTechnology.com.tw/Ticket/wsdl/TicketService/v1-0/ticketSeatInquiry")
    public tw.com.bluetechnology.ticket.xsd.ticketservice.v1_0.TicketSeatInquiryResultResponse ticketSeatInquiry(
        @WebParam(partName = "body", name = "ticketSeatInquiryRequest", targetNamespace = "http://www.bluetechnology.com.tw/Ticket/xsd/TicketService/v1-0")
        tw.com.bluetechnology.ticket.xsd.ticketservice.v1_0.TicketSeatInquiryRequest body
    );
	/**
	 * 獲得班機訂位查詢資訊
	 * @param 班機訂位查詢資訊輸入物件 {@link TicketSeatOrderInquiryRequest}
	 * @return 班機訂位查詢資訊回傳物件 {@link TicketSeatOrderInquiryResultResponse}
	 */
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "ticketSeatOrderInquiryResultResponse", targetNamespace = "http://www.bluetechnology.com.tw/Ticket/xsd/TicketService/v1-0", partName = "body")
    @WebMethod(action = "http://www.blueTechnology.com.tw/Ticket/wsdl/TicketService/v1-0/ticketSeatOrderInquiry")
    public tw.com.bluetechnology.ticket.xsd.ticketservice.v1_0.TicketSeatOrderInquiryResultResponse ticketSeatOrderInquiry(
        @WebParam(partName = "body", name = "ticketSeatOrderInquiryRequest", targetNamespace = "http://www.bluetechnology.com.tw/Ticket/xsd/TicketService/v1-0")
        tw.com.bluetechnology.ticket.xsd.ticketservice.v1_0.TicketSeatOrderInquiryRequest body
    );

	/**
	 * 獲得剩餘機位查詢+訂位作業資訊
	 * 
	 * @param 剩餘機位查詢+訂位作業資訊輸入物件 {@link TicketSeatOrderInquiryRequest}
	 * @return 剩餘機位查詢+訂位作業資訊回傳物件 {@link TicketSeatOrderInquiryResultResponse}
	 */
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "ticketSeatOrderResultResponse", targetNamespace = "http://www.bluetechnology.com.tw/Ticket/xsd/TicketService/v1-0", partName = "body")
    @WebMethod(action = "http://www.blueTechnology.com.tw/Ticket/wsdl/TicketService/v1-0/ticketSeatOrder")
    public tw.com.bluetechnology.ticket.xsd.ticketservice.v1_0.TicketSeatOrderResultResponse ticketSeatOrder(
        @WebParam(partName = "body", name = "ticketSeatOrderResultRequest", targetNamespace = "http://www.bluetechnology.com.tw/Ticket/xsd/TicketService/v1-0")
        tw.com.bluetechnology.ticket.xsd.ticketservice.v1_0.TicketSeatOrderResultRequest body
    );
}
