
package com.bluetechnology.wsdl.v1_0;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import com.bluetechnology.wsdl.v1_0.TicketSeatInquiryPortType;

/**
 * This class was generated by Apache CXF 2.0.6
 * Mon Nov 04 11:58:33 CST 2013
 * Generated source version: 2.0.6
 * 
 */

@WebServiceClient(name = "TicketSeatInquiryHttpService", targetNamespace = "http://www.bluetechnology.com.tw/wsdl/v1-0", wsdlLocation = "file:src/main/resources/TicketSeatInquiry.wsdl")
public class TicketSeatInquiryHttpService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.bluetechnology.com.tw/wsdl/v1-0", "TicketSeatInquiryHttpService");
    public final static QName TicketSeatInquiryHttpPort = new QName("http://www.bluetechnology.com.tw/wsdl/v1-0", "TicketSeatInquiryHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("file:src/main/resources/TicketSeatInquiry.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:src/main/resources/TicketSeatInquiry.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public TicketSeatInquiryHttpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TicketSeatInquiryHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TicketSeatInquiryHttpService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns TicketSeatInquiryHttpPort
     */
    @WebEndpoint(name = "TicketSeatInquiryHttpPort")
    public TicketSeatInquiryPortType getTicketSeatInquiryHttpPort() {
        return super.getPort(TicketSeatInquiryHttpPort, TicketSeatInquiryPortType.class);
    }

}
