
package com.bluetechnology.wsdl.v1_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import org.springframework.stereotype.Service;

import com.bluetechnology.jaxb.TicketSeatInquiry.TicketSeatInquiryResultRequest;
import com.bluetechnology.jaxb.TicketSeatInquiry.TicketSeatInquiryResultResponse;

/**
 * This class was generated by Apache CXF 2.0.6
 * Mon Nov 04 11:58:33 CST 2013
 * Generated source version: 2.0.6
 * 
 */
@Service
@WebService(targetNamespace = "http://www.bluetechnology.com.tw/wsdl/v1-0", name = "TicketSeatInquiryPortType")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TicketSeatInquiryPortType {

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "ticketSeatInquiryResultResponse", targetNamespace = "http://www.bluetechnology.com.tw", partName = "body")
    @WebMethod
    public TicketSeatInquiryResultResponse ticketSeatInquiryResult(
        @WebParam(partName = "body", name = "ticketSeatInquiryResultRequest", targetNamespace = "http://www.bluetechnology.com.tw")
        TicketSeatInquiryResultRequest body
    );
}
