<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions
	targetNamespace="http://www.bluetechnology.com.tw/Ticket/wsdl/TicketService/v1-0"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<wsdl:import location="TicketService.wsdl"
		namespace="http://www.bluetechnology.com.tw/Ticket/wsdl/Service/TicketService/v1-0" />


</wsdl:definitions>