<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions
	targetNamespace="http://www.bluetechnology.com.tw/Ticket/wsdl/port/TicketService/v1-0"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:btwsdl="http://www.bluetechnology.com.tw/Ticket/wsdl/message/TicketService/v1-0"
	xmlns:sec="http://cxf.apache.org/configuration/security" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="TicketPort">

    <wsdl:import location="TicketMessage.wsdl" namespace="http://www.bluetechnology.com.tw/Ticket/wsdl/message/TicketService/v1-0"></wsdl:import>
	<wsdl:portType name="TicketPortType">
		<wsdl:operation name="ticketSeatInquiry">
			<wsdl:input message="btwsdl:ticketSeatInquiryRequest" />
			<wsdl:output message="btwsdl:ticketSeatInquiryResponse" />
		</wsdl:operation>
		<wsdl:operation name="ticketSeatOrder">
			<wsdl:input message="btwsdl:ticketSeatOrderRequest" />
			<wsdl:output message="btwsdl:ticketSeatOrderResponse" />
		</wsdl:operation>
		<wsdl:operation name="ticketSeatOrderInquiry">
			<wsdl:input message="btwsdl:ticketSeatOrderInquiryRequest" />
			<wsdl:output message="btwsdl:ticketSeatOrderInquiryResponse" />
		</wsdl:operation>
	</wsdl:portType>
</wsdl:definitions>