
package tw.com.bluetechnology.ticket.wsdl.ticketservice.v1_0;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import tw.com.bluetechnology.ticket.wsdl.ticketservice.v1_0.TicketPortType;

/**
 * This class was generated by Apache CXF 2.0.6
 * Fri Nov 08 13:20:33 CST 2013
 * Generated source version: 2.0.6
 * 
 */

@WebServiceClient(name = "TicketSoapHttpService", targetNamespace = "http://www.bluetechnology.com.tw/Ticket/wsdl/TicketService/v1-0", wsdlLocation = "file:src/main/resources/Ticket.wsdl")
public class TicketSoapHttpService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.bluetechnology.com.tw/Ticket/wsdl/TicketService/v1-0", "TicketSoapHttpService");
    public final static QName TicketSoapHttpPort = new QName("http://www.bluetechnology.com.tw/Ticket/wsdl/TicketService/v1-0", "TicketSoapHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("file:src/main/resources/Ticket.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:src/main/resources/Ticket.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public TicketSoapHttpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TicketSoapHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TicketSoapHttpService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns TicketSoapHttpPort
     */
    @WebEndpoint(name = "TicketSoapHttpPort")
    public TicketPortType getTicketSoapHttpPort() {
        return super.getPort(TicketSoapHttpPort, TicketPortType.class);
    }

}
